["pyproject.toml"]

  ["pyproject.toml".project]
    requires-python = ">= 3.13"

  ["pyproject.toml".tool]
    ["pyproject.toml".tool.pyright]
      pythonVersion = "3.13"

    ["pyproject.toml".tool.ruff]
      target-version = "py313"
