["pyproject.toml"]

  ["pyproject.toml".project]
    requires-python = ">= 3.14"

  ["pyproject.toml".tool]

    ["pyproject.toml".tool.pyright]
      pythonVersion = "3.14"

    ["pyproject.toml".tool.ruff]
      target-version = "py314"
