[".pre-commit-config.yaml"]

  [[".pre-commit-config.yaml".repos]]
    repo = "local"

    # pyright
    [[".pre-commit-config.yaml".repos.hooks]]
      entry = "pyright"
      id = "pyright"
      language = "system"
      name = "pyright"
      types = ["python"]
